In [46]:
import pandas as pd
import geopandas as gpd
import matplotlib as plt

suomi_viirs_path = "DATASETS/SUOMI_VIIRS_C2_USA_contiguous_and_Hawaii_24h.csv"
noaa_viirs_path = "DATASETS/J1_VIIRS_C2_USA_contiguous_and_Hawaii_24h.csv"
modis_path = "DATASETS/MODIS_C6_USA_contiguous_and_Hawaii_24h.csv"

In [26]:
suomi_viirs_data = pd.read_csv(suomi_viirs_path, parse_dates=['acq_date', 'acq_time'])
suomi_viirs_data

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,confidence,version,bright_ti5,frp,daynight
0,31.15063,-87.99097,316.7,0.49,0.65,2020-09-26,0648,N,nominal,2.0NRT,289.4,2.4,N
1,31.15034,-87.98576,314.1,0.49,0.65,2020-09-26,0648,N,nominal,2.0NRT,290.4,2.4,N
2,30.48426,-91.18553,300.2,0.74,0.76,2020-09-26,0648,N,nominal,2.0NRT,289.5,2.1,N
3,30.34416,-88.48821,304.4,0.51,0.66,2020-09-26,0648,N,nominal,2.0NRT,291.5,1.4,N
4,30.32692,-91.28209,299.0,0.75,0.77,2020-09-26,0648,N,nominal,2.0NRT,288.4,1.1,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6747,33.94266,-111.73448,352.2,0.59,0.70,2020-09-27,1924,N,nominal,2.0NRT,307.1,16.8,D
6748,33.94129,-111.73920,331.6,0.59,0.70,2020-09-27,1924,N,low,2.0NRT,304.6,8.5,D
6749,33.94410,-111.80122,337.1,0.60,0.70,2020-09-27,1924,N,nominal,2.0NRT,306.8,5.7,D
6750,33.94182,-111.80904,347.8,0.60,0.70,2020-09-27,1924,N,nominal,2.0NRT,308.8,5.7,D
6751,33.94806,-111.81159,331.5,0.60,0.70,2020-09-27,1924,N,low,2.0NRT,305.0,5.7,D

In [27]:
noaa_viirs_data = pd.read_csv(noaa_viirs_path, parse_dates=['acq_date', 'acq_time'])
noaa_viirs_data

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,confidence,version,bright_ti5,frp,daynight
0,19.60118,-71.01389,323.9,0.40,0.44,2020-09-26,0554,1,nominal,2.0NRT,292.9,3.0,N
1,19.52833,-70.73214,306.0,0.38,0.43,2020-09-26,0554,1,nominal,2.0NRT,291.6,1.2,N
2,18.92856,-70.35446,338.2,0.54,0.42,2020-09-26,0554,1,nominal,2.0NRT,294.6,25.9,N
3,18.00744,-66.65473,304.2,0.39,0.36,2020-09-26,0554,1,nominal,2.0NRT,291.9,0.4,N
4,48.18973,-64.92108,298.2,0.41,0.45,2020-09-26,0548,1,nominal,2.0NRT,277.2,1.2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5215,19.56577,-92.23937,352.0,0.53,0.67,2020-09-27,1830,1,nominal,2.0NRT,289.3,17.8,D
5216,19.58750,-92.20234,336.6,0.53,0.67,2020-09-27,1830,1,nominal,2.0NRT,285.9,5.2,D
5217,19.59876,-92.29350,351.4,0.53,0.67,2020-09-27,1830,1,nominal,2.0NRT,288.2,7.9,D
5218,27.87473,-81.76313,335.4,0.39,0.36,2020-09-27,1830,1,nominal,2.0NRT,298.2,1.8,D
5219,28.14973,-81.41625,334.7,0.39,0.36,2020-09-27,1830,1,nominal,2.0NRT,297.8,6.4,D

In [28]:
modis_data = pd.read_csv(modis_path, parse_dates=['acq_date', 'acq_time'])
modis_data

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,confidence,version,bright_t31,frp,daynight
0,39.884,-78.246,300.3,1.4,1.2,2020-09-26,0255,T,24,6.0NRT,284.0,10.4,N
1,18.639,-96.216,308.0,1.4,1.2,2020-09-26,0425,T,73,6.0NRT,291.3,10.4,N
2,40.595,-105.702,303.1,1.9,1.4,2020-09-26,0435,T,53,6.0NRT,278.5,23.4,N
3,40.696,-105.729,322.6,1.9,1.3,2020-09-26,0435,T,77,6.0NRT,283.9,54.7,N
4,40.705,-105.718,321.3,1.9,1.3,2020-09-26,0435,T,39,6.0NRT,282.8,49.1,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061,36.986,-89.296,310.0,1.1,1.1,2020-09-27,1855,A,24,6.0NRT,290.6,5.8,D
1062,37.173,-89.891,308.6,1.2,1.1,2020-09-27,1855,A,47,6.0NRT,293.4,6.5,D
1063,37.171,-89.904,323.1,1.2,1.1,2020-09-27,1855,A,79,6.0NRT,294.8,22.9,D
1064,37.494,-89.416,314.4,1.1,1.1,2020-09-27,1855,A,58,6.0NRT,296.0,10.2,D
1065,43.646,-96.553,311.1,1.9,1.4,2020-09-27,1855,A,71,6.0NRT,293.9,20.4,D

<h2>
    Se eliminan los datos con baja confidencia
</h2>

In [29]:
modis_data = modis_data.drop(modis_data[modis_data.confidence < 90].index)
modis_data

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,confidence,version,bright_t31,frp,daynight
5,40.700,-105.737,337.1,1.9,1.3,2020-09-26,0435,T,100,6.0NRT,283.8,102.3,N
10,41.089,-106.299,345.8,2.0,1.4,2020-09-26,0435,T,100,6.0NRT,273.0,149.3,N
11,41.084,-106.323,327.3,2.0,1.4,2020-09-26,0435,T,92,6.0NRT,275.2,70.4,N
12,41.135,-106.143,444.8,2.0,1.4,2020-09-26,0435,T,100,6.0NRT,277.6,0.0,N
13,41.130,-106.167,450.7,2.0,1.4,2020-09-26,0435,T,100,6.0NRT,284.6,0.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,36.284,-118.666,344.8,1.1,1.0,2020-09-27,1855,T,91,6.0NRT,296.9,51.1,D
1010,30.480,-91.505,340.8,2.0,1.4,2020-09-27,1855,A,91,6.0NRT,301.7,105.3,D
1048,36.470,-90.313,369.1,1.3,1.1,2020-09-27,1855,A,100,6.0NRT,305.2,152.8,D
1049,36.467,-90.327,360.2,1.3,1.1,2020-09-27,1855,A,100,6.0NRT,303.2,114.4,D
1050,36.468,-90.317,363.6,1.3,1.1,2020-09-27,1855,A,100,6.0NRT,307.0,128.3,D

In [30]:
suomi_viirs_data = suomi_viirs_data.drop(suomi_viirs_data[suomi_viirs_data.confidence == "low"].index)
suomi_viirs_data

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,confidence,version,bright_ti5,frp,daynight
0,31.15063,-87.99097,316.7,0.49,0.65,2020-09-26,0648,N,nominal,2.0NRT,289.4,2.4,N
1,31.15034,-87.98576,314.1,0.49,0.65,2020-09-26,0648,N,nominal,2.0NRT,290.4,2.4,N
2,30.48426,-91.18553,300.2,0.74,0.76,2020-09-26,0648,N,nominal,2.0NRT,289.5,2.1,N
3,30.34416,-88.48821,304.4,0.51,0.66,2020-09-26,0648,N,nominal,2.0NRT,291.5,1.4,N
4,30.32692,-91.28209,299.0,0.75,0.77,2020-09-26,0648,N,nominal,2.0NRT,288.4,1.1,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6745,33.94116,-111.71581,341.1,0.59,0.70,2020-09-27,1924,N,nominal,2.0NRT,309.4,6.7,D
6746,33.94715,-111.71913,338.1,0.59,0.70,2020-09-27,1924,N,nominal,2.0NRT,307.7,6.7,D
6747,33.94266,-111.73448,352.2,0.59,0.70,2020-09-27,1924,N,nominal,2.0NRT,307.1,16.8,D
6749,33.94410,-111.80122,337.1,0.60,0.70,2020-09-27,1924,N,nominal,2.0NRT,306.8,5.7,D
6750,33.94182,-111.80904,347.8,0.60,0.70,2020-09-27,1924,N,nominal,2.0NRT,308.8,5.7,D

In [31]:
noaa_viirs_data = noaa_viirs_data.drop(noaa_viirs_data[noaa_viirs_data.confidence == "low"].index)
noaa_viirs_data

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,confidence,version,bright_ti5,frp,daynight
0,19.60118,-71.01389,323.9,0.40,0.44,2020-09-26,0554,1,nominal,2.0NRT,292.9,3.0,N
1,19.52833,-70.73214,306.0,0.38,0.43,2020-09-26,0554,1,nominal,2.0NRT,291.6,1.2,N
2,18.92856,-70.35446,338.2,0.54,0.42,2020-09-26,0554,1,nominal,2.0NRT,294.6,25.9,N
3,18.00744,-66.65473,304.2,0.39,0.36,2020-09-26,0554,1,nominal,2.0NRT,291.9,0.4,N
4,48.18973,-64.92108,298.2,0.41,0.45,2020-09-26,0548,1,nominal,2.0NRT,277.2,1.2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5215,19.56577,-92.23937,352.0,0.53,0.67,2020-09-27,1830,1,nominal,2.0NRT,289.3,17.8,D
5216,19.58750,-92.20234,336.6,0.53,0.67,2020-09-27,1830,1,nominal,2.0NRT,285.9,5.2,D
5217,19.59876,-92.29350,351.4,0.53,0.67,2020-09-27,1830,1,nominal,2.0NRT,288.2,7.9,D
5218,27.87473,-81.76313,335.4,0.39,0.36,2020-09-27,1830,1,nominal,2.0NRT,298.2,1.8,D
5219,28.14973,-81.41625,334.7,0.39,0.36,2020-09-27,1830,1,nominal,2.0NRT,297.8,6.4,D

<h2>
    Se concatenan los valores de todos los satelites en un solo archivo
</h2>

In [65]:
latitude = pd.concat([modis_data["latitude"], suomi_viirs_data["latitude"], noaa_viirs_data["latitude"]])
longitude = pd.concat([modis_data["longitude"], suomi_viirs_data["longitude"], noaa_viirs_data["longitude"]])
date = pd.concat([modis_data["acq_date"], suomi_viirs_data["acq_date"], noaa_viirs_data["acq_date"]])
hour = pd.concat([modis_data["acq_time"], suomi_viirs_data["acq_time"], noaa_viirs_data["acq_time"]])


data = [latitude, longitude, date, hour]
headers = ["latitude", "longitude", "date", "hour"]

fire_data = pd.concat(data, axis=1, keys=headers).reset_index(drop=True)
fire_data

       latitude  longitude       date  hour
0      40.70000 -105.73700 2020-09-26  0435
1      41.08900 -106.29900 2020-09-26  0435
2      41.08400 -106.32300 2020-09-26  0435
3      41.13500 -106.14300 2020-09-26  0435
4      41.13000 -106.16700 2020-09-26  0435
...         ...        ...        ...   ...
12070  19.56577  -92.23937 2020-09-27  1830
12071  19.58750  -92.20234 2020-09-27  1830
12072  19.59876  -92.29350 2020-09-27  1830
12073  27.87473  -81.76313 2020-09-27  1830
12074  28.14973  -81.41625 2020-09-27  1830

[12075 rows x 4 columns]

In [67]:
fire_data.to_csv('DATASETS/fire_data.csv',index=False)